### ISSUE TITLE
Use M_PI constant

### ISSUE THREAD

**Issue by wieset** [esa-prl/drivers-orogen-inclinometer_solar2#2]
https://stackoverflow.com/questions/1727881/how-to-use-the-pi-constant-in-c

https://github.com/esa-prl/drivers-orogen-inclinometer_solar2/blob/9332b5bd9968f58f077c753648fcee60afb35256/tasks/Task.cpp#L112-L113

**Comment by mvoellmy** [comment]
Done in commit 5c8ad4f8cb0d22a523d64ac67414f280ac0f6294
